### ISSUE TITLE
你好，能否在生成model对时候，把相应的包含下划线的字段转化成小驼峰形式的方法。

### ISSUE THREAD

**Issue by lhh-sofy** [laxian/dart-json2entity#10]
如address_id 转化为 addressId
不然总是报：Name non-constant identifiers using lowerCamelCase.

**Comment by laxian** [comment]
@lhh-sofy 你好，下划线转驼峰的情况，在[博客](https://juejin.im/post/5c36251ce51d45524473f79f#heading-8)里有提到，可以手动修改一下，添加@JsonKey注解。 当前，j2e还不支持自动转换，目前没有时间添加，下次更新可以考虑。

**Comment by laxian** [comment]
@lhh-sofy 临时写了个独立转换工具，位置在develop分支的bin/lower_camel.dart.
使用方法，dart lower_camel.dart "xxx.dart"

**Comment by laxian** [comment]
@lhh-sofy 1.1.2 已实现
