### ISSUE TITLE
使用这个东西报错

### ISSUE THREAD

**Issue by misskter** [laxian/dart-json2entity#6]
当我成功配置完成以后使用出现这样的错误，
Can't load Kernel binary: Invalid kernel binary format version.
这个该怎么解决呢？

**Comment by laxian** [comment]
能否提供一下复现步骤？
还有你的flutter doctor信息

**Comment by laxian** [comment]
> 当我成功配置完成以后使用出现这样的错误，
> Can't load Kernel binary: Invalid kernel binary format version.
> 这个该怎么解决呢？

能否提供一下复现步骤？
还有你的flutter doctor信息
