### ISSUE TITLE
使用 json file 报错

### ISSUE THREAD

**Issue by MagicalWater** [laxian/dart-json2entity#7]
test.json
```
{
  "code": 100,
  "data": {
    "cc": 100,
    "dd": "aaaaa"
  }
}
```

命令为
```
 j2e -f assets/json/test.json -o lib/bean/test/test_bean
```

console error output
```
type 'int' is not a subtype of type 'String'
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

```

将 -f 换为 -j
```
 j2e -j assets/json/test.json -o lib/bean/test/test_bean
```

console error output
```
Input Json Format Error! Unexpected character

```

不過如果直接打入字串就可以
```
 j2e -j '{"code": 100, "data": {"cc": 100, "dd": "aaaa"}}' -o lib/bean/test/test_bean
```

**Comment by laxian** [comment]
@MagicalWater 谢谢你的反馈。
* 首先，-f是从文件读取多个json，而不是单个。
具体格式参考[input.json](https://github.com/laxian/dart-json2entity/blob/master/example/input.json)

* 其次，上面的例子，只是从文件读取单个json，我觉得可以这样：
```j2e -j "\`cat assets/json/test.json\`" -o lib/bean/test/test_bean```
注意别漏了命令中的双引号。不支持管道
