### ISSUE TITLE
Input Json Format Error! Unexpected character（1.0.8）

### ISSUE THREAD

**Issue by xingyiyang** [laxian/dart-json2entity#9]
![捕获](https://user-images.githubusercontent.com/17688516/63829767-f9878480-c99c-11e9-9562-bb8a3e954438.PNG)
![捕获2](https://user-images.githubusercontent.com/17688516/63829904-5be08500-c99d-11e9-9491-08462997baf4.PNG)

**Comment by xingyiyang** [comment]
我直接拷贝Readme.md的命令，竟然失败了

**Comment by laxian** [comment]
@xingyiyang 好的，谢谢，我会在windows上尝试一下。

**Comment by KangSpace** [comment]
like this :

![image](https://user-images.githubusercontent.com/26271023/63837594-58092e80-c9ae-11e9-83e2-ddf2efecfcfa.png)

**Comment by laxian** [comment]
@KangSpace clever boy.
我试了下，Windows cmd 环境下输入字符串，需要转义。
稍后我会写到readme里。
谢谢！@xingyiyang 
![image](https://user-images.githubusercontent.com/13779717/63837982-15942180-c9af-11e9-8db3-984ee2a4d8d7.png)

**Comment by xingyiyang** [comment]
厉害
